name: Testing cooking_forum_backend

on: push

jobs:
  pytest:
    runs-on: ubuntu-latest
    services:

      cooking_forum_backend-db:
        image: postgres:13.8-bullseye
        env:
          POSTGRES_PASSWORD: cooking_forum_backend
          POSTGRES_USER: cooking_forum_backend
          POSTGRES_DB: cooking_forum_backend
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
        - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install deps
      uses: knowsuchagency/poetry-install@v1
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run pytest check
      run: poetry run pytest -vv --cov="cooking_forum_backend" .
      env:
        COOKING_FORUM_BACKEND_HOST: "0.0.0.0"
        COOKING_FORUM_BACKEND_DB_HOST: localhost
